In [1]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


In [2]:
linspace?

Signature:
linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples to generate. Default is 50. Must be non-negative.
endpoint : bool, optional
    If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
retstep : boo

In [3]:
linspace(0, 1, 200) 

array([0.        , 0.00502513, 0.01005025, 0.01507538, 0.0201005 ,
       0.02512563, 0.03015075, 0.03517588, 0.04020101, 0.04522613,
       0.05025126, 0.05527638, 0.06030151, 0.06532663, 0.07035176,
       0.07537688, 0.08040201, 0.08542714, 0.09045226, 0.09547739,
       0.10050251, 0.10552764, 0.11055276, 0.11557789, 0.12060302,
       0.12562814, 0.13065327, 0.13567839, 0.14070352, 0.14572864,
       0.15075377, 0.15577889, 0.16080402, 0.16582915, 0.17085427,
       0.1758794 , 0.18090452, 0.18592965, 0.19095477, 0.1959799 ,
       0.20100503, 0.20603015, 0.21105528, 0.2160804 , 0.22110553,
       0.22613065, 0.23115578, 0.2361809 , 0.24120603, 0.24623116,
       0.25125628, 0.25628141, 0.26130653, 0.26633166, 0.27135678,
       0.27638191, 0.28140704, 0.28643216, 0.29145729, 0.29648241,
       0.30150754, 0.30653266, 0.31155779, 0.31658291, 0.32160804,
       0.32663317, 0.33165829, 0.33668342, 0.34170854, 0.34673367,
       0.35175879, 0.35678392, 0.36180905, 0.36683417, 0.37185

In [4]:
t = linspace(-pi, pi, 100)

In [5]:
len(t)

100

In [6]:
plot(t, cos(t))

In [7]:
#Graphical illustration:

import matplotlib.pyplot as plt
N = 8
y = np.zeros(N)
x1 = np.linspace(0, 10, N, endpoint=True)
x2 = np.linspace(0, 10, N, endpoint=False)
plt.plot(x1, y, 'o')
#[<matplotlib.lines.Line2D object at 0x...>]
plt.plot(x2, y + 0.5, 'o')
#[<matplotlib.lines.Line2D object at 0x...>]
plt.ylim([-0.5, 1])
#(-0.5, 1)
plt.show()

In [8]:
plot(t, sin(t))

In [9]:
plot((sin(t)*sin(t))/t)

In [10]:
x = linspace(-2, 4, 20)
x

array([-2.        , -1.68421053, -1.36842105, -1.05263158, -0.73684211,
       -0.42105263, -0.10526316,  0.21052632,  0.52631579,  0.84210526,
        1.15789474,  1.47368421,  1.78947368,  2.10526316,  2.42105263,
        2.73684211,  3.05263158,  3.36842105,  3.68421053,  4.        ])

In [11]:
plot(x, sin(x), 'r', linewidth = 3) #Manipulations on the graph >> 'r'=red..width = 2 

In [12]:
clf()
plot(x, sin(x), 'r *') # 'r.' = red colored dotted line. Note:Could be any symbol instead of a dot.

In [13]:
#Modifying the plot further
clf()
title(r"Parabolic Function $-x*x+4*x-5$") #r means raw string format
xlabel(r"$x$")
ylabel(r"$y$")
annotate("local maxima", xy = (2, -1))
plot(x, -x*x+4*x-5, 'r--', linewidth = 3)


In [14]:
print(xlim())
print(ylim())

(-2.3, 4.3)
(-17.799445983379503, -0.21163434903047074)


In [15]:
xlim(-4, 5)
ylim(-15, 2)

(-15.0, 2.0)

In [16]:
annotate("root", xy = (-4, 0))

Text(-4, 0, 'root')

In [17]:
#Modifying the plot further
clf()
title(r"Parabolic Function $-x*x+4*x-5$") #r means raw string format
xlabel(r"$x$")
ylabel(r"$y$")
xlim(-4, 5)
ylim(-15, 2)
annotate("root", xy = (-4, 0))
annotate("local maxima", xy = (2, -1))
plot(x, -x*x+4*x-5, 'r--', linewidth = 3)


# Asignment

In [18]:
clf()
var = linspace(-2*pi, 2*pi, 100)
var

array([-6.28318531, -6.15625227, -6.02931923, -5.9023862 , -5.77545316,
       -5.64852012, -5.52158709, -5.39465405, -5.26772102, -5.14078798,
       -5.01385494, -4.88692191, -4.75998887, -4.63305583, -4.5061228 ,
       -4.37918976, -4.25225672, -4.12532369, -3.99839065, -3.87145761,
       -3.74452458, -3.61759154, -3.4906585 , -3.36372547, -3.23679243,
       -3.10985939, -2.98292636, -2.85599332, -2.72906028, -2.60212725,
       -2.47519421, -2.34826118, -2.22132814, -2.0943951 , -1.96746207,
       -1.84052903, -1.71359599, -1.58666296, -1.45972992, -1.33279688,
       -1.20586385, -1.07893081, -0.95199777, -0.82506474, -0.6981317 ,
       -0.57119866, -0.44426563, -0.31733259, -0.19039955, -0.06346652,
        0.06346652,  0.19039955,  0.31733259,  0.44426563,  0.57119866,
        0.6981317 ,  0.82506474,  0.95199777,  1.07893081,  1.20586385,
        1.33279688,  1.45972992,  1.58666296,  1.71359599,  1.84052903,
        1.96746207,  2.0943951 ,  2.22132814,  2.34826118,  2.47

In [19]:
plot(var, cos(var), 'b .', linewidth = 4)

In [20]:
ylabel?

Signature: ylabel(ylabel, fontdict=None, labelpad=None, **kwargs)
Docstring:
Set the label for the y-axis.

Parameters
----------
ylabel : str
    The label text.

labelpad : scalar, optional, default: None
    Spacing in points from the axes bounding box including ticks
    and tick labels.

Other Parameters
----------------
**kwargs : `.Text` properties
    `.Text` properties control the appearance of the label.

See also
--------
text : for information on how override and the optional args work
File:      c:\users\anuj\anaconda3\lib\site-packages\matplotlib\pyplot.py
Type:      function


# Saving plots

In [21]:
x = linspace(-3*pi, 3*pi, 100)
x

array([-9.42477796, -9.23437841, -9.04397885, -8.8535793 , -8.66317974,
       -8.47278019, -8.28238063, -8.09198108, -7.90158152, -7.71118197,
       -7.52078241, -7.33038286, -7.1399833 , -6.94958375, -6.75918419,
       -6.56878464, -6.37838508, -6.18798553, -5.99758598, -5.80718642,
       -5.61678687, -5.42638731, -5.23598776, -5.0455882 , -4.85518865,
       -4.66478909, -4.47438954, -4.28398998, -4.09359043, -3.90319087,
       -3.71279132, -3.52239176, -3.33199221, -3.14159265, -2.9511931 ,
       -2.76079354, -2.57039399, -2.37999443, -2.18959488, -1.99919533,
       -1.80879577, -1.61839622, -1.42799666, -1.23759711, -1.04719755,
       -0.856798  , -0.66639844, -0.47599889, -0.28559933, -0.09519978,
        0.09519978,  0.28559933,  0.47599889,  0.66639844,  0.856798  ,
        1.04719755,  1.23759711,  1.42799666,  1.61839622,  1.80879577,
        1.99919533,  2.18959488,  2.37999443,  2.57039399,  2.76079354,
        2.9511931 ,  3.14159265,  3.33199221,  3.52239176,  3.71

In [22]:
plot(x, sin(x))
#Saving the plot using savefig function
#Savefig takes 1 arguement that is filename. The filename format: Filename.Extention
#Allowed Extentions - .pdf, .ps (post script), .eps(Encapsulated Post Script), .svg (scalabel Vector Graphics), .png (Portable Network Graphics) 
savefig('sine.png')

## Multiple Plots

In [23]:
x = linspace(0, 50, 10)
x

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [24]:
clf()
plot(x, sin(x))

In [25]:
y = linspace(0, 50, 500)
y

array([ 0.        ,  0.1002004 ,  0.2004008 ,  0.3006012 ,  0.4008016 ,
        0.501002  ,  0.6012024 ,  0.70140281,  0.80160321,  0.90180361,
        1.00200401,  1.10220441,  1.20240481,  1.30260521,  1.40280561,
        1.50300601,  1.60320641,  1.70340681,  1.80360721,  1.90380762,
        2.00400802,  2.10420842,  2.20440882,  2.30460922,  2.40480962,
        2.50501002,  2.60521042,  2.70541082,  2.80561122,  2.90581162,
        3.00601202,  3.10621242,  3.20641283,  3.30661323,  3.40681363,
        3.50701403,  3.60721443,  3.70741483,  3.80761523,  3.90781563,
        4.00801603,  4.10821643,  4.20841683,  4.30861723,  4.40881764,
        4.50901804,  4.60921844,  4.70941884,  4.80961924,  4.90981964,
        5.01002004,  5.11022044,  5.21042084,  5.31062124,  5.41082164,
        5.51102204,  5.61122244,  5.71142285,  5.81162325,  5.91182365,
        6.01202405,  6.11222445,  6.21242485,  6.31262525,  6.41282565,
        6.51302605,  6.61322645,  6.71342685,  6.81362725,  6.91

In [26]:
plot(y, sin(y))

In [27]:
#Allots strings to the plot in the order they were created
legend(['sin(x)','sin(y)'])

In [28]:
clf()
x = np.linspace(-5, 5, 100)

# calculate the y value for each element of the x vector
y = 4*(x*x)
plot(x, y)
plot(x, (2*x)+3)
legend([r'$y=4(x^2)$', r'$y=2x+3$'])

In [29]:
#Saving the plots
clf()
x = linspace(0, 50, 500)
#To accomplish more control over our plots
figure(1)
plot(x, sin(x), 'b')
title('sin(x)')
savefig('sin.png')
figure(2)
plot(x, cos(x),'g')
title('cos(x)')
savefig('cosine.png')

# Asignment

In [30]:
clf()
x = linspace(-5, 5, 100)
figure(1)
plot(x,x)
savefig("FormYisX.png")
figure(2)
plot(x, 2*x+3)
savefig("FormYis2Xp3")

## Subplots

In [31]:
# 2 plots in the same area
clf()
x = linspace(0, 50, 500)
subplot(2, 1, 1)
plot(x, cos(x))
y = linspace(0,5, 100)
subplot(2,1,2)
plot(y, y**2)

# Asignment

In [32]:
'''
Pressure, volume and temp are held by the equation PV = nRT (nR is constant)
nR = 0.01
T = 200K
v = range(21cc, 100cc)

> Pressure vs Volume plot
> Pressure vs Temperature plot
'''
clf()
v = linspace(21, 100, 500)
nR = 0.01
T = 200
subplot(2,1,1)
plot(v, (nR*T)/v)
t = linspace(200, 200, 500)
subplot(2,1,2)
plot(t, (nR*T)/v)

In [33]:
subplot?

Signature: subplot(*args, **kwargs)
Docstring:
Add a subplot to the current figure.

Wrapper of `.Figure.add_subplot` with a difference in behavior
explained in the notes section.

Call signatures::

   subplot(nrows, ncols, index, **kwargs)
   subplot(pos, **kwargs)
   subplot(ax)

Parameters
----------
*args
    Either a 3-digit integer or three separate integers
    describing the position of the subplot. If the three
    integers are *nrows*, *ncols*, and *index* in order, the
    subplot will take the *index* position on a grid with *nrows*
    rows and *ncols* columns. *index* starts at 1 in the upper left
    corner and increases to the right.

    *pos* is a three digit integer, where the first digit is the
    number of rows, the second the number of columns, and the third
    the index of the subplot. i.e. fig.add_subplot(235) is the same as
    fig.add_subplot(2, 3, 5). Note that all integers must be less than
    10 for this form to work.

projection : {None, 'aitoff', 'ham

## Plotting data

In [34]:
l = []
for i in range(0*2,10):
    l.append(0.1*i)
print(l)
len(l)

[0.0, 0.1, 0.2, 0.30000000000000004, 0.4, 0.5, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9]


10

In [35]:
t = [0.69, 0.90,1.23,1.33,1.47,1.50 ,1.57, 1.70, 1.80, 1.97]
len(t)

10

In [36]:
tsq = square(t)
tsq

array([0.4761, 0.81  , 1.5129, 1.7689, 2.1609, 2.25  , 2.4649, 2.89  ,
       3.24  , 3.8809])

#Plot l vs tsq
plot(l, tsq, 'r+')

In [37]:
clf()
errorbar(l, tsq, xerr = l, yerr = t, fmt='bo')

<ErrorbarContainer object of 3 artists>

# Asignment

In [38]:
s = []
for i in range(0*2,10):
    s.append(0.19*i)
s = s[1:]
len(s)

9

In [39]:
n = [10.74,14.01,18.23,20.03,22.88,24.65,27.34,28.90,30.20]
len(n)

9

## Plotting the charts

In [40]:
n = 10
z = np.random.uniform(0, 1, n)
l = np.arange(0, 10)
plt.pie(z, labels= l)
plt.show()

In [41]:
clf()
n = 12
X = np.arange(n)
Y1 = (1-X/float(n)) * np.random.uniform(0.5,1.0,n)
bar(X, Y1, fill = False, hatch = "/")

<BarContainer object of 12 artists>

## Statistics

In [42]:
import os
os.chdir("D:\Spoken Tutorials\Statistics-Codefiles\codefiles-Statistics")

In [43]:
df = np.loadtxt("student_record.txt", usecols = (3,4,5,6,7), delimiter = ';')
df

array([[53., 36., 28., 16., 44.],
       [58., 37., 42., 35., 40.],
       [72., 56., 71., 55., 70.],
       ...,
       [49., 39., 12., 20., 24.],
       [33., 36., 22., 15., 35.],
       [17., 14., 15., 14., 20.]])

In [44]:
df.shape

(185667, 5)

In [45]:
df[0]

array([53., 36., 28., 16., 44.])

In [46]:
df = np.loadtxt("football.txt", usecols = (1,2), delimiter = ',')
df

array([[86., 67.],
       [34., 65.],
       [45., 41.],
       [23., 24.],
       [43., 45.],
       [65., 34.]])

In [47]:
totalg = np.sum(df, 1)
totalg

array([153.,  99.,  86.,  47.,  88.,  99.])

In [48]:
goals = np.mean(df, 0)
goals

array([49.33333333, 46.        ])

In [49]:
std = np.std(df, 0)
std

array([20.72572208, 15.57776193])

In [50]:
td = [[3,5,2,7,1],
      [4,3,6,2,1]]
np.mean(td, 0)
np.mean(td, 1)

array([3.6, 3.2])

In [51]:
stm = [98,99,100,78,88,90,100]
np.median(stm)

98.0

## Arrays

In [52]:
for i in np.arange(0, 10, dtype='float32'):
    print(i)

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0


In [53]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
a = [1,2,3,4]
np.ones(a,'float')

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [55]:
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [56]:
b = np.arange(1, 26).reshape(5,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [57]:
b[2,3] = 0

In [58]:
b[2,3]

0

In [59]:
b[2] = 0

In [60]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 0,  0,  0,  0,  0],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [61]:
b[0:3, 2]

array([3, 8, 0])

In [62]:
b[1, 1:3]

array([7, 8])

In [63]:
b[0:4, 0]

array([ 1,  6,  0, 16])

In [64]:
b[2, 0:4]

array([0, 0, 0, 0])

In [65]:
b = np.arange(1, 26).reshape(5,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [66]:
b[::3, 1:3]

array([[ 2,  3],
       [17, 18]])

In [67]:
b[::4, 1:4]

array([[ 2,  3,  4],
       [22, 23, 24]])

## Operations on Matrix

In [68]:
m1 = matrix([1,2,3,4])
m1.shape

(1, 4)

In [69]:
m2 = asmatrix(arange(5, 13).reshape(2, 4))

In [70]:
m2

matrix([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [71]:
'''
eig(a)[0] => eigen values
eig(a)[1] => eigen vectors
eigvals(a) => eigen values
'''
from numpy import diag
from numpy.linalg import eig
mat1 = asmatrix(diag((1,2,3)))
mat1

matrix([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

In [72]:
eig(mat1)

(array([1., 2., 3.]),
 matrix([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]))

In [73]:
'''
Find frobenius (sqroot of the sum of the absolute sq of elements) and
infinity norm (maximum value of the absolute value of elements in each row)
of a matrix
find singular value decomposition of a matrix

flatten() = Multi dimensional array into one dimensional array

'''
a  =asmatrix(arange(1, 10).reshape(3,3))
a

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [74]:
a.flatten()

matrix([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [75]:
#Finding the frobenius matrix
a = asmatrix(arange(1, 17).reshape(4,4))
a

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

In [76]:
a[0,1], a[1,3] = 0,0

In [77]:
a

matrix([[ 1,  0,  3,  4],
        [ 5,  6,  7,  0],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

In [78]:
ia = inv(a)
norm(ia)

3.7059917700933958

In [79]:
#Infinity norm
norm(ia, ord=inf)

4.624999999999997

In [80]:
#SVD ~ Singular Value Decomposition
#      Factorization of a real or complex matrix
mat2 = matrix([[3,2,2],[2,3,-2]])
svd(mat2)

(matrix([[-0.70710678, -0.70710678],
         [-0.70710678,  0.70710678]]),
 array([5., 3.]),
 matrix([[-7.07106781e-01, -7.07106781e-01, -5.55111512e-17],
         [-2.35702260e-01,  2.35702260e-01, -9.42809042e-01],
         [-6.66666667e-01,  6.66666667e-01,  3.33333333e-01]]))

In [81]:
U, sigma, V_conjugate = svd(mat2)

In [82]:
smat = zeros((2,3))
smat

array([[0., 0., 0.],
       [0., 0., 0.]])

In [83]:
smat[:2, :2] = diag(sigma)
smat

array([[5., 0., 0.],
       [0., 3., 0.]])

In [84]:
allclose(mat2, U* smat * V_conjugate)

True

In [85]:
norm(mat1) == norm(mat1, ord='fro')

True

## Least Square Fit

In [86]:
os.chdir('D:\Spoken Tutorials\Least-square-fit-Codefiles\Codefiles-LeastSquareFit')

In [87]:
l, t = loadtxt("pendulum.txt", unpack = True)
l

array([0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ,
       0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31,
       0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42,
       0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53,
       0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64,
       0.65, 0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75,
       0.76, 0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86,
       0.87, 0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97,
       0.98, 0.99])

In [88]:
t

array([0.69004, 0.69497, 0.74252, 0.7536 , 0.83568, 0.86789, 0.84182,
       0.85379, 0.85762, 0.8839 , 0.89985, 0.98436, 1.0244 , 1.0572 ,
       0.99077, 1.0058 , 1.0727 , 1.0943 , 1.1432 , 1.1045 , 1.1867 ,
       1.1385 , 1.2245 , 1.2406 , 1.2071 , 1.2658 , 1.2995 , 1.3142 ,
       1.2663 , 1.2578 , 1.2991 , 1.3058 , 1.3478 , 1.3506 , 1.4044 ,
       1.3948 , 1.38   , 1.448  , 1.4168 , 1.4719 , 1.4656 , 1.4399 ,
       1.5174 , 1.4988 , 1.4751 , 1.5326 , 1.5297 , 1.5372 , 1.6094 ,
       1.6352 , 1.5843 , 1.6643 , 1.5987 , 1.6585 , 1.6317 , 1.7074 ,
       1.6654 , 1.6551 , 1.6964 , 1.7143 , 1.7706 , 1.7622 , 1.726  ,
       1.8089 , 1.7905 , 1.7428 , 1.8381 , 1.8182 , 1.7865 , 1.7995 ,
       1.8296 , 1.8625 , 1.8623 , 1.8383 , 1.8593 , 1.8944 , 1.9598 ,
       1.9    , 1.9244 , 1.9397 , 1.944  , 1.9718 , 1.9383 , 1.9555 ,
       2.0006 , 1.9841 , 2.0066 , 2.0493 , 2.0503 , 2.0214 ])

In [89]:
tsq = square(t)
plot(l, tsq, 'bo')

In [90]:
inter_mat = array((l, ones_like(l)))
inter_mat

array([[0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ,
        0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31,
        0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42,
        0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53,
        0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64,
        0.65, 0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75,
        0.76, 0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86,
        0.87, 0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97,
        0.98, 0.99],
       [1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1. 

In [91]:
A = inter_mat.T
A

array([[0.1 , 1.  ],
       [0.11, 1.  ],
       [0.12, 1.  ],
       [0.13, 1.  ],
       [0.14, 1.  ],
       [0.15, 1.  ],
       [0.16, 1.  ],
       [0.17, 1.  ],
       [0.18, 1.  ],
       [0.19, 1.  ],
       [0.2 , 1.  ],
       [0.21, 1.  ],
       [0.22, 1.  ],
       [0.23, 1.  ],
       [0.24, 1.  ],
       [0.25, 1.  ],
       [0.26, 1.  ],
       [0.27, 1.  ],
       [0.28, 1.  ],
       [0.29, 1.  ],
       [0.3 , 1.  ],
       [0.31, 1.  ],
       [0.32, 1.  ],
       [0.33, 1.  ],
       [0.34, 1.  ],
       [0.35, 1.  ],
       [0.36, 1.  ],
       [0.37, 1.  ],
       [0.38, 1.  ],
       [0.39, 1.  ],
       [0.4 , 1.  ],
       [0.41, 1.  ],
       [0.42, 1.  ],
       [0.43, 1.  ],
       [0.44, 1.  ],
       [0.45, 1.  ],
       [0.46, 1.  ],
       [0.47, 1.  ],
       [0.48, 1.  ],
       [0.49, 1.  ],
       [0.5 , 1.  ],
       [0.51, 1.  ],
       [0.52, 1.  ],
       [0.53, 1.  ],
       [0.54, 1.  ],
       [0.55, 1.  ],
       [0.56, 1.  ],
       [0.57,

In [92]:
result = lstsq(A, tsq)
result

C:\Users\Anuj\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(array([4.14148447, 0.07358041]),
 array([0.63609563]),
 2,
 array([10.8710938 ,  2.15077185]))

In [93]:
m, c = result[0]
m, c

(4.141484466369428, 0.07358041497643907)

In [94]:
tsq_fit = m*l+c
tsq_fit

array([0.48772886, 0.52914371, 0.57055855, 0.6119734 , 0.65338824,
       0.69480308, 0.73621793, 0.77763277, 0.81904762, 0.86046246,
       0.90187731, 0.94329215, 0.984707  , 1.02612184, 1.06753669,
       1.10895153, 1.15036638, 1.19178122, 1.23319607, 1.27461091,
       1.31602575, 1.3574406 , 1.39885544, 1.44027029, 1.48168513,
       1.52309998, 1.56451482, 1.60592967, 1.64734451, 1.68875936,
       1.7301742 , 1.77158905, 1.81300389, 1.85441874, 1.89583358,
       1.93724842, 1.97866327, 2.02007811, 2.06149296, 2.1029078 ,
       2.14432265, 2.18573749, 2.22715234, 2.26856718, 2.30998203,
       2.35139687, 2.39281172, 2.43422656, 2.47564141, 2.51705625,
       2.55847109, 2.59988594, 2.64130078, 2.68271563, 2.72413047,
       2.76554532, 2.80696016, 2.84837501, 2.88978985, 2.9312047 ,
       2.97261954, 3.01403439, 3.05544923, 3.09686408, 3.13827892,
       3.17969376, 3.22110861, 3.26252345, 3.3039383 , 3.34535314,
       3.38676799, 3.42818283, 3.46959768, 3.51101252, 3.55242

In [95]:
clf()
plot(l, tsq_fit, 'bo') #tsq

In [96]:
np.ones_like([1,2,3])

array([1, 1, 1])

In [97]:
b = 899999999999999999999
b

899999999999999999999

In [98]:
abs(3+4j)

5.0

# Asignment 1
# Handling errors and exceptions

In [99]:
%debug

ERROR:root:No traceback has been produced, nothing to debug.


# Asignment 2
# Testing and debugging

In [100]:
'''
1.
2. 4 space indentation
'''

'\n1.\n2. 4 space indentation\n'

# Asignment 3
# Writing python scripting

In [101]:
sys.path

['C:\\Users\\Anuj\\NeuralNetworkProjects\\Style Transfer',
 'C:\\Users\\Anuj\\Anaconda3\\python37.zip',
 'C:\\Users\\Anuj\\Anaconda3\\DLLs',
 'C:\\Users\\Anuj\\Anaconda3\\lib',
 'C:\\Users\\Anuj\\Anaconda3',
 '',
 'C:\\Users\\Anuj\\Anaconda3\\lib\\site-packages',
 'C:\\Users\\Anuj\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\Anuj\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\Anuj\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\Anuj\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Anuj\\.ipython']

In [102]:
'''
2. False
'''

'\n2. False\n'

# Asignment 4
# Using python modules

In [103]:
#1.
from matplotlib.pyplot import plot
#2
from matplotlib.pyplot import xlim, ylim

# Asignment 5
# Advanced features of functions

In [104]:
#5.3
#2.
count = 4
def sep(count, char, show=False):
    if show:
        print(char*count)
    return char*count

In [105]:
def h(a = "hello", b = ""):
    return a+" world"
h()    

'hello world'

# Assignment 6
# Sets in python

In [106]:
#6.1
l = [20, 23, 22, 23, 20, 21, 23]
set(l)

{20, 21, 22, 23}

In [107]:
#6.2
#1.
a = [1, 1, 2, 3, 3, 5, 5, 8]
set(a)

{1, 2, 3, 5, 8}

In [108]:
#2.
odd = set([1, 3, 5, 7, 9])
squares = set([1, 4, 9, 16])
odd^squares 

{3, 4, 5, 7, 16}

In [109]:
#3.
h = set(['b',1,3,2])
'b' in h

True

# Asignment 7
# Dictionaries

In [110]:
#7.1
#1.
student = { 'name':'raj', 'age':16, 'gender':'male', 'class':10 }
for index, name in student.items():
    print(index, name)

name raj
age 16
gender male
class 10


In [111]:
#7.2
#1.
d = {1:'a', 2:'b'}
l = ""
for value in d.values():
    if value == 'b':
        l = value
print(l) 
#2.
del d[2]
print(d)

b
{1: 'a'}


# Asignment 8
# Getting started with tuples

In [112]:
t = (4, 2.5)

In [113]:
a = 5
type(a)

int

In [114]:
a = (2,3)
a[0], a[1] = (3,4)
#ERROR

TypeError: 'tuple' object does not support item assignment

# Asignment 9
# Manipulating Strings

In [115]:
s = "saturday"
s[1:-1]

'aturda'

In [116]:
week_name = ["sun", "mon", "tue", "wed", "thu", "fri", "sat"] 
for day in ['SATURDAY', 'python', 'Sunday']:
    print(day, day.lower()[:3] in week_name)

SATURDAY True
python False
Sunday True


In [117]:
email = "info@fossee[dot]in"
v = email.replace("[dot]",".")
v

'info@fossee.in'

In [118]:
email_str = "info@fossee.in, enquiries@fossee.in, help@fossee.in"
email_str.replace(",", " :")

'info@fossee.in : enquiries@fossee.in : help@fossee.in'

In [119]:
s = "this was a sting"
s.replace("was", "wasn't")

"this wasn't a sting"

In [120]:
s = "F.R.I.E.N.D.S"
s.replace(".","").lower()

'friends'

# Asignment 10
# Manipulating lists

In [121]:
primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29] 
primes[:4]

[2, 3, 5, 7]

In [122]:
num = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13] 
for i in range(1, len(num)):
    if i%3 == 0:
        print(i)

3
6
9
12


In [123]:
marks = [99, 67, 47, 100, 50, 75, 62] 
marks.sort(reverse = True)
marks

[100, 99, 75, 67, 62, 50, 47]

In [124]:
primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29] 
primes[-4:]
primes[:3]

[2, 3, 5]

# Asignment 11
# Loops

In [125]:
#11.1
#Print all squares under 10 using while loop
i = 1
while i<10:
    print(i**2)
    i+=1

1
4
9
16
25
36
49
64
81


In [126]:
#11.2
#Print all the even numbers below 10
for index in range(1, 11):
    if index%2 == 0:
        print(index)

2
4
6
8
10


In [127]:
#11.2
#1.
#Given range(1,4), write a code to print only the number 1
for index in range(1,4):
    if index == 1:
        print(index)
    else:
        pass

1


In [128]:
'''
2.
Which statement do you use to skip iterations?
➢ break
➢ paas
➢ continue

Ans: continue
'''

'\n2.\nWhich statement do you use to skip iterations?\n➢ break\n➢ paas\n➢ continue\n\nAns: continue\n'

# Asignment 12
# Input putput

In [129]:
n = int(input())
n if n%10 == 0 else print(n*10)

 3


30


In [130]:
x = 20
print(x*100) if x>10 else print(x)

2000


In [131]:
x = 1.9
y = 2
print ('x is %d, y is %.1f' %(x, y))

x is 1, y is 2.0


In [132]:
a = input()

 9


In [133]:
type(a)

str

# Asignment 13
# Sequence data

In [134]:
s = "Elizabeth is queen of england"
st = s.split()
s = ' '.join(st[:3])
s

'Elizabeth is queen'

In [135]:
s = "Split this string on whitespaces"
s.split()

['Split', 'this', 'string', 'on', 'whitespaces']

# Asignment 14
# Basic datatype and operators

In [136]:
import math
math.sqrt(3)
3**0.5

1.7320508075688772

In [137]:
import numpy as np
np.ones([1,2,3])

array([[[1., 1., 1.],
        [1., 1., 1.]]])

# Asignment 14
# Advanced matrix 

In [138]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


C:\Users\Anuj\Anaconda3\lib\site-packages\IPython\core\magics\pylab.py:160: UserWarning: pylab import has clobbered these variables: ['var', 'std']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


In [139]:
m = asmatrix(arange(1, 17).reshape(4,4))
m

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

In [140]:
from numpy.linalg import inv, norm
im = inv(m)
im
norm(im)

8.300495083009867e+16

In [141]:
#infinity norm
from numpy import inf
norm(im,ord=inf)

1.3135498913163926e+17

# Asignment 15
## Determinants of matrix

In [142]:
m3 = asmatrix(arange(5, 13).reshape(2,4))
m3

matrix([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [143]:
m5 = [[ 2, -3, 1], [ 2, 0, -1], [ 1, 4, 5]]
det(m5)

49.000000000000014

# Asignment 16
## Accessing array elements

In [144]:
C = array([[1, 2, 3, 4, 5],
           [6, 7, 8, 9, 10],
           [11, 12, 13, -14, 15],
           [16, 17, 18, 19, 20],
           [2, 2, 2, 2, 2]])

In [145]:
C[1, 1:3]

array([7, 8])

In [146]:
C[0:4, 0]

array([ 1,  6, 11, 16])

In [147]:
C[1:5, 0]

array([ 6, 11, 16,  2])

In [148]:
C[1:3, 2:4]

array([[  8,   9],
       [ 13, -14]])

In [149]:
C[0:5:2, 0:5:2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [ 2,  2,  2]])

In [150]:
C[::2, ::2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [ 2,  2,  2]])

In [151]:
C

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13, -14,  15],
       [ 16,  17,  18,  19,  20],
       [  2,   2,   2,   2,   2]])

In [152]:
C[0:4:3, 1:5:3]

array([[ 2,  5],
       [17, 20]])

In [153]:
C[0:5:4,1:4]

array([[2, 3, 4],
       [2, 2, 2]])

In [154]:
A = array([12, 15, 18, 21])
A[2]

18

In [155]:
B = array ( [ [10, 11, 12, 13],
            [20, 21, 22, 23],
            [30, 31, 32, 33],
            [40, 41, 42, 43] ] )

In [156]:
B[1:3, 1:3]

array([[21, 22],
       [31, 32]])

# Asignments 17
## String manipulations

In [157]:
s =  "Guido;Rossum;Python"
s.split(";")

['Guido', 'Rossum', 'Python']

In [158]:
s = "Hello"
t = "World"
r = 2
s * r + t * r

'HelloHelloWorldWorld'